### ISSUE TITLE
New ITE Device ID

### ISSUE THREAD

**Issue by kfechter** [pobrn/ite8291r3-ctl#15]
I recently got a laptop with an ITE RGB controller, and it seems to have a new device ID (048d:6006), that is not on the supported list. 

It still reports as an 8291 rev 0.03, but none of the control apps work as they don't support the 6006 product ID. 

I can get any required information in the morning, I'll just have to boot a live image since the laptop currently runs windows. 

I am also willing to make any required changes with any associated testing.

**Comment by pobrn** [comment]
If you're feeling adventurous, you can try adding `0x6006` to the [list of supported products here](https://github.com/pobrn/ite8291r3-ctl/blob/9b5f35b6c5ae197ecb4cd462b845041d2c40bd24/ite8291r3_ctl/ite8291r3.py#L10). Otherwise, if there is an application which can control it on Windows, then you can create a USB traffic dump with Wireshark while using said program.

**Comment by kfechter** [comment]
Tested adding 0x6006 to supported id's and it seemed to work perfectly. I have the change made in my forked repo and can open a pull request. Going to close this issue.
