### ISSUE TITLE
[Feature] Lightbar management XMG Fusion 15

### ISSUE THREAD

**Issue by Demaz93** [pobrn/ite8291r3-ctl#3]
Is it possible to add the possibility to manage also the front lightbar for the XMG Fusion 15?

**Comment by pobrn** [comment]
The front lightbar of the XMG Fusion 15 (or any Intel LAPQC71X device) can be managed using the [`qc71_laptop`](https://github.com/pobrn/qc71_laptop) platform driver on Linux, or in the Control Center on Windows. I do not plan on adding support for that because I would like to keep this project focused on the ITE 8291 controller, it's not meant to become a full-fledged QC71 control center.
